[package]
name = "libcoresettings"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
libqinit = { path = "../../quill_init/libqinit" }
log = "0.4.29"
openssl = "0.10.75"
